name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v6

      - name: Deploy na Cloudflare
        uses: cloudflare/wrangler-action@v6
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name="itau-calculadora" --branch="production"